const Sort = require('./classes/sort')
const Search = require('./classes/search')
const SinglyLinkedList = require('./classes/singlyLinkedList')
const DoublyLinkedList = require('./classes/DoublyLinkedList')
const Stack = require('./classes/stack')
const Queue = require('./classes/queue')
const BinaryMaxHeap = require('./classes/BinaryMaxHeap')
const PriorityQueue = require('./classes/PriorityQueue')
const BinarySearchTree = require('./classes/binarySearchTree')
const Graph = require('./classes/graph')
const HashTable = require('./classes/hashTable')

module.exports.Sort=Sort
module.exports.Search=Search
module.exports.SinglyLinkedList=SinglyLinkedList
module.exports.DoublyLinkedList=DoublyLinkedList
module.exports.Stack=Stack
module.exports.Queue=Queue
module.exports.BinaryMaxHeap=BinaryMaxHeap
module.exports.PriorityQueue=PriorityQueue
module.exports.BinarySearchTree=BinarySearchTree
module.exports.Graph=Graph
module.exports.HashTable=HashTable